# Generated by Django 5.1 on 2024-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="dropoff_latitude",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_longitude",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_latitude",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_longitude",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
