# Generated by Django 5.1 on 2024-08-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_ridedistance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridedistance",
            name="ride",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.ride"
            ),
        ),
    ]
